spring:
  main:
    banner-mode: off

  datasource:
    initialization-mode: embedded
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:traindb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

  h2:
    console:
      enabled: true
      path: /h2
      settings.web-allow-others: true
