version: '2'
services:
  db:
    image: mysql:5.7.21
    container_name: userdb
    hostname: userdb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: userdb
      MYSQL_USER: userap
      MYSQL_PASSWORD: userapsecret
    volumes:
      - db-vol:/var/lib/mysql
#  cache:
#    image: redis:4.0.1
#    container_name: mojipic-redis
#    ports:
#      - 6379
volumes:
  db-vol:
