spring:
  application:
    name: userap
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
logging:
  pattern:
    level: "%d{ABSOLUTE} [%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: userap
    password: userapsecret
    driver-class-name: com.mysql.jdbc.Driver
