version: '2'
services:
  db:
    image: mysql:5.7.21
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: messagedb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db-vol:/var/lib/mysql
volumes:
  db-vol:
